server:
  port: '@server.port@'

management:
  security:
    flag: false
  server:
    port: '@management.port@'
  metrics:
    export:
      statsd:
        flavor: etsy
        enabled: false
      prometheus:
        enabled: false
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

spring:
  application:
    name: '@project.name@'
  output:
    ansi:
      enabled: always
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: '@db.url@'
    username: '@db.user@'
    password: '@db.password@'
  jpa:
    properties:
      hibernate:
        default_schema: '@db.schema@'
        jdbc:
          time_zone: UTC
          batch_size: 20
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect

info:
  version: '@project.version@'
  stage: dev

kafka:
  bootstrap-servers: localhost:9092
  retry-attempts: 3
  max-poll-records: 100
  max-poll-interval-ms: 60000
  max-session-timeout-ms: 6000
  topic:
    initial: mg-events-party
    max-poll-records: 50
  ssl:
    enabled: false
  consumer:
    enabled: true
    prefix: porter
    concurrency: 7
    throttling-timeout-ms: 1000
