name: Build Artifact

on:
  pull_request:
    branches:
      - '*'

jobs:

  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: LabBox64/build-actions/packages/jdk-build@v1.0.1
