name: Build Maven Artifact

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    uses: valitydev/base-workflow/.github/workflows/maven-service-build.yml@057aebf15167d92aee4ba07e4d23c16ccc4a6edd
