name: Deploy Docker Image

on:
  push:
    branches:
      - 'master'

jobs:
  build-and-deploy:
    uses: valitydev/base-workflow/.github/workflows/maven-service-deploy.yml@057aebf15167d92aee4ba07e4d23c16ccc4a6edd
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}}
